apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-tooling
  namespace: argocd
spec:
  description: Platform team owns the platform itself
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
